### ISSUE TITLE
Setup process

### ISSUE THREAD

**Issue by nygma2004** [mariusmotea/diyHue#20]
Would you be able to help a newbie to set this up? I have a rpi3, Tradfri Gateway and Google Home. If I understand correctly, with this my Google Home should be able to control my Tradfri lights. Correct?

I have python on the pi, but what steps do I need to make to get this code installed?

Sorry for asking the obvious.

**Comment by mariusmotea** [comment]
Hi. So far i don't test this with Google Home but if i'm not wrong it is using hue api so it must work (it not we can fix). I also have in my home Tradfri Gateway with a few lights and i can confirm this is working. i will paste here a few basic commands used for installation:

```
marius@XPS-13:~$ ssh pi@raspberry
pi@raspberry's password: 

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

pi@raspberrypi:~ $ #check if git is installed
pi@raspberrypi:~ $ sudo apt install git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
git is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

pi@raspberrypi:~ $ git clone https://github.com/mariusmotea/diyHue.git
Cloning into 'diyHue'...
remote: Counting objects: 753, done.
remote: Total 753 (delta 0), reused 0 (delta 0), pack-reused 753
Receiving objects: 100% (753/753), 7.90 MiB | 1.50 MiB/s, done.
Resolving deltas: 100% (316/316), done.
Checking connectivity... done.

pi@raspberrypi:~ $ cd diyHue/BridgeEmulator/
pi@raspberrypi:~/diyHue/BridgeEmulator $ sudo ./HueEmulator.py
config loaded
lights adress file was not loaded
starting ssdp...
Starting httpd...
```
Now the service is up and running. Later you must add this to startup via rc.local file (check closed issues).
Next: 
1. install Hue official application on you phone, connect to emulated bridge.
2. open in any browser http://raspberry_ip/tradfri
3. enter in form the security code from Tradfri Gateway and  the ip address of Tradfri Gateway. If everything is correct you will see a text on the bottom with the number of lights imported from Tradfri.
4. open again hue application and setup your lights/rooms. Here the bridge emulator can be unresponsive because on step 3 the browser access favicon.ico file. You will need to wait for about 30 seconds until this will have a timeout or you can press CTRL + C on raspberry pi console and execute the script again (config will be saved on exit only if you press CTRL+C).

Please confirm if you setup with Google Home is working fine.

**Comment by nygma2004** [comment]
Thanks a lot, your help is appreciated. I followed the steps above, but the pairing of the Hue hub to Google Home did not work. I pasted the log here. In the Google Home setup, it was asking me to click the pair button on my Philips Hue box which I obviously don't have. But I see some exception at the end of the log, so I assume the code was not expecting this command.
[GoogeHome_pairing.txt](https://github.com/mariusmotea/diyHue/files/1133742/GoogeHome_pairing.txt)

I am away from home, I will not be able to test your fix for about 1.5 weeks.

**Comment by mariusmotea** [comment]
Thanks for log output, it help me to understand what is the issue. Even if the error is related to pair button, the pair was successful, Google Home receive a new username from bridge emulator and then it try to get the lights details and this step fail because of "KeyError: '5706'". This key is used by IKEA to store the color temperature and it seems that you are using standard bulbs with no option to change the color temperature. it is now fixed in this commit https://github.com/mariusmotea/diyHue/commit/5877d5a2e891712701a5545519dad7bffbb980b5 .

When you will be back just execute "git pull" inside diyHue folder to get this fix and then start again the Bridge Emulator.

Enjoy your vacation!

**Comment by nygma2004** [comment]
Hi Marius,
I am afraid it is not working. I performed a git pull, and I tried pairing again, but nothing happens. I don't see any messages on the Pi console when the emulator is working. The Hue app works, so it is definitely running and communicating with Trafri, but that's itt. The Google Home pairing just times out after a minute. I also noticed that when I Ctrl+C the program on the PI, it says "server stopped" "config saved", but I am not getting the prompt back. Not sure how I can help with this.

**Comment by mariusmotea** [comment]
Ok, let's start again with new log output. If you press CTRL + C the ssdp discover thread may remain stuck, just type ```CTRL + Z```  ```sudo kill -9 `pgrep Hue``` and ```fg``` to kill zombie precess, then start again the script. Ensure the new changes where applied (better download again). Another thing you can do before to start the HueEmulator script is to delete existing GoogleHome user hash from config.json => whitelist => fd4b6d95e1063dbb291e605f871a1ed9e1b90746 (from your log) backup this file before, maybe there is a problem because the user is already there from first failed try.

**Comment by nygma2004** [comment]
OK, now I think I have messed it up completely. I did git pull again, and it was saying it is already the latest version. I removed the GoogleHome user from the config.json, but no change. Google Home is still not pairing. I even tried the delete everything (the dyiHue directory), and git again, as well as the Philips Hue app. But it just made it worse, as the hue app is not discovering my two bulbs (as they are not new bulbs). I tried removing the two config files hoping that it will re-discover again, but not.

I cannot restart the emulator either, without rebooting the PI, because I get this message:
config loaded
lights address loaded
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./HueEmulator.py", line 71, in ssdp_search
    sock.bind(server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use

server stopped
config saved

Sorry again, I am just a linux user, not much experience with advanced stuff.

**Comment by mariusmotea** [comment]
Download config.json again from this repo, it contain default config data and dictionary structure. "Address already in use" means the script is running in background. Try netstat -lntp | grep 80. You will see the pid of the process. Kill -9 pid will kill the process. Type fg to be sure there is no zombie process in background.

**Comment by mariusmotea** [comment]
Was this issue solved, can i close it?

**Comment by nygma2004** [comment]
I am sorry, but I started a new job and I am either travelling this month or on holiday out of town. I have to put this project on ice for the time being. I tried to resolve it, but did not succeed. Close this issue because I can only come back to this in about a month or so.

**Comment by mariusmotea** [comment]
ok, fell free to open it back if you will have issues
