### ISSUE TITLE
cannot connect to the official Hue app

### ISSUE THREAD

**Issue by huongminh** [mariusmotea/diyHue#339]
Hi,
I've been using hue emulator since March 2018. it could perfectly control my Mi-light bubs from the official Hue App. That is great! However, about 1 month ago, the Hue app could not connect to my Hue Emulator anymore. The status is always "connecting...". it seems now the protocol is "https" not "http" anymore. I read the forum and found a cert.pem file should lie in /opt/hue-emulator but I found none in /opt/hue-emulator. Please help!

**Comment by mariusmotea** [comment]
find the mac address of the device you hosting the hue emulator then get the certificate with:

```curl http://mariusmotea.go.ro:9002/gencert?mac=00:11:22:33:44:55```

replace `00:11:22:33:44:55` with your mac address.
Put the output content in /opt/hue-emulator/cert.pem

If is still not working wipe the hue application data on your mobile.

**Comment by huongminh** [comment]
Thank you for your instruction! Do I have to re-install hue-emulator to get https support? or just do as your instruction. In fact, I followed the steps as per  your  instruction but it did not work. And I cannot clean the bridge there was always a message saying you have to connect to your home wifi network to clean the bridge though my phone (iphoneX) is connected to the same network with the Hue Emulator.

**Comment by mariusmotea** [comment]
Wipe the phone application data and try to pair again with the emulator. You you don't know how to press the link button, just check the wiki.

**Comment by LimaKilo** [comment]
I have a similar issue, though I never had a working connection to the bridge (getting started just now). The hue app can find the hue emulator, but when trying to pair (set up button in the app, then clicking "activate" on the ip/hue/linkbutton site), it stops, saying "no new bridges found" (or the equivalent in german).

**Comment by cornishcross** [comment]
i am also having a connection issue. I can find the emulated bridge with the app when I click on the activate button nothing happens the hue app wont connect to the bridge.

**Comment by mariusmotea** [comment]
please provide output of following commands:
`ip a`
and
`curl https//127.0.0.1/api/nouser/config`
executed from hue emulator device.

**Comment by LimaKilo** [comment]
I get:
`pi@raspberrypi:~ $ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: wlan0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 30:b5:c2:11:78:bf brd ff:ff:ff:ff:ff:ff
    inet 192.168.188.24/24 brd 192.168.188.255 scope global wlan0
       valid_lft forever preferred_lft forever
    inet6 fe80::84dc:a131:b22a:4004/64 scope link
       valid_lft forever preferred_lft forever
pi@raspberrypi:~ $ curl https//127.0.0.1/api/nouser/config
curl: (6) Could not resolve host: https
pi@raspberrypi:~ $ curl https://127.0.0.1/api/nouser/config
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
pi@raspberrypi:~ $
`

**Comment by mariusmotea** [comment]
Sorry, i forgot the parameters

`curl https//127.0.0.1/api/nouser/config -k -v`

**Comment by LimaKilo** [comment]
There's a : missing behind your https ;)

>  curl https://127.0.0.1/api/nouser/config -k -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=NL; O=Philips Hue; CN=30b5c2fffe1178bf
*  start date: Sep  3 21:32:09 2018 GMT
*  expire date: Aug 31 21:32:09 2028 GMT
*  issuer: C=NL; O=Philips Hue; CN=30b5c2fffe1178bf
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /api/nouser/config HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 04 Sep 2018 05:42:13 GMT
< Content-type: application/json
< Content-Length: 229
<
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
{"starterkitid":"","datastoreversion":70,"name":"Philips hue","factorynew":false,"mac":"53:55:72:03:13:87","bridgeid":"535572FFFE03138751","apiversion":"1.24.0","modelid":"BSB002","swversion":"1806051111","replacesbridgeid":null}

**Comment by mariusmotea** [comment]
i believe is fixed now. Execute again automatic installer of manually download the new HueEmulator3.py file and override the one from /opt/hue-emulator

**Comment by LimaKilo** [comment]
Works for me now, thanks!

**Comment by huongminh** [comment]
I deleted the bridge in my mobile hue app and reconnect but unsuccessful. Bridge was found but could not connect after I click the link button. I rename the opt/hue-emulator to back-up and re-run the installation script but still not work. I tried the command and got:
pi@raspberrypi:/opt/hue-emulator $ curl https://127.0.0.1/api/nouser/config -k -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=NL; O=Philips Hue; CN=b827ebfffedcfe88
*  start date: Sep  6 16:27:32 2018 GMT
*  expire date: Oct  6 16:27:32 2018 GMT
*  issuer: C=NL; O=Philips Hue; CN=b827ebfffedcfe88
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /api/nouser/config HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx 
< Date: Thu, 06 Sep 2018 16:31:54 GMT
< Content-type: application/json
< Content-Length: 227
< 
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
{"name":"Philips hue","replacesbridgeid":null,"swversion":"1806051111","apiversion":"1.24.0","factorynew":false,"datastoreversion":70,"bridgeid":"B827EBFFFEDCFE88","mac":"b8:27:eb:dc:fe:88","modelid":"BSB002","starterkitid":""}You have new mail in /var/mail/pi

please help!

**Comment by huongminh** [comment]
How do I delete phone application data? does that mean I have to delete the Hue App and re-install it?

**Comment by mariusmotea** [comment]
On Android you have in Settings - Applications - Hue - Data - delete data. Reinstall also must work.

**Comment by cheesemarathon** [comment]
If your on android go to Settings - Apps & Notifications - Hue - Storage and then click the "Clear storage" button. Your menu names may differ slightly but that should point you in the right direct. As for iPhone, I can't help you, try a reinstall of the app.

**Comment by huongminh** [comment]
Thank you for your support. I deleted my iphone Hue app and reinstalled it. Now it works like a charm!
